# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Siera(object):
    def setupUi(self, Siera):
        Siera.setObjectName("Siera")
        Siera.resize(1033, 690)
        Siera.setMinimumSize(QtCore.QSize(1033, 690))
        self.centralWidget = QtWidgets.QWidget(Siera)
        self.centralWidget.setObjectName("centralWidget")
        self.label_SIERA = QtWidgets.QLabel(self.centralWidget)
        self.label_SIERA.setGeometry(QtCore.QRect(390, 70, 201, 51))
        self.label_SIERA.setMaximumSize(QtCore.QSize(201, 51))
        self.label_SIERA.setTextFormat(QtCore.Qt.RichText)
        self.label_SIERA.setObjectName("label_SIERA")
        self.label_SIERA_STD = QtWidgets.QLabel(self.centralWidget)
        self.label_SIERA_STD.setGeometry(QtCore.QRect(390, 190, 201, 51))
        self.label_SIERA_STD.setMaximumSize(QtCore.QSize(201, 51))
        self.label_SIERA_STD.setTextFormat(QtCore.Qt.RichText)
        self.label_SIERA_STD.setObjectName("label_SIERA_STD")
        self.label_SIERA_label = QtWidgets.QLabel(self.centralWidget)
        self.label_SIERA_label.setGeometry(QtCore.QRect(390, 20, 201, 51))
        self.label_SIERA_label.setMaximumSize(QtCore.QSize(201, 51))
        self.label_SIERA_label.setTextFormat(QtCore.Qt.RichText)
        self.label_SIERA_label.setObjectName("label_SIERA_label")
        self.label_SIERA_STD_label = QtWidgets.QLabel(self.centralWidget)
        self.label_SIERA_STD_label.setGeometry(QtCore.QRect(390, 140, 221, 51))
        self.label_SIERA_STD_label.setTextFormat(QtCore.Qt.RichText)
        self.label_SIERA_STD_label.setObjectName("label_SIERA_STD_label")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(20, 30, 291, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_PA = QtWidgets.QLabel(self.widget)
        self.label_PA.setMaximumSize(QtCore.QSize(71, 51))
        self.label_PA.setScaledContents(False)
        self.label_PA.setWordWrap(True)
        self.label_PA.setObjectName("label_PA")
        self.gridLayout.addWidget(self.label_PA, 0, 0, 1, 1)
        self.label_GB = QtWidgets.QLabel(self.widget)
        self.label_GB.setMaximumSize(QtCore.QSize(71, 51))
        self.label_GB.setScaledContents(False)
        self.label_GB.setWordWrap(True)
        self.label_GB.setObjectName("label_GB")
        self.gridLayout.addWidget(self.label_GB, 0, 1, 1, 1)
        self.label_K = QtWidgets.QLabel(self.widget)
        self.label_K.setMaximumSize(QtCore.QSize(71, 51))
        self.label_K.setScaledContents(False)
        self.label_K.setWordWrap(True)
        self.label_K.setObjectName("label_K")
        self.gridLayout.addWidget(self.label_K, 0, 2, 1, 1)
        self.spinBox_PA = QtWidgets.QSpinBox(self.widget)
        self.spinBox_PA.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_PA.setObjectName("spinBox_PA")
        self.gridLayout.addWidget(self.spinBox_PA, 1, 0, 1, 1)
        self.spinBox_GB = QtWidgets.QSpinBox(self.widget)
        self.spinBox_GB.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_GB.setObjectName("spinBox_GB")
        self.gridLayout.addWidget(self.spinBox_GB, 1, 1, 1, 1)
        self.spinBox_K = QtWidgets.QSpinBox(self.widget)
        self.spinBox_K.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_K.setObjectName("spinBox_K")
        self.gridLayout.addWidget(self.spinBox_K, 1, 2, 1, 1)
        self.label_SO = QtWidgets.QLabel(self.widget)
        self.label_SO.setMaximumSize(QtCore.QSize(71, 51))
        self.label_SO.setScaledContents(False)
        self.label_SO.setWordWrap(True)
        self.label_SO.setObjectName("label_SO")
        self.gridLayout.addWidget(self.label_SO, 2, 0, 1, 1)
        self.label_FB = QtWidgets.QLabel(self.widget)
        self.label_FB.setMaximumSize(QtCore.QSize(71, 51))
        self.label_FB.setScaledContents(False)
        self.label_FB.setWordWrap(True)
        self.label_FB.setObjectName("label_FB")
        self.gridLayout.addWidget(self.label_FB, 2, 1, 1, 1)
        self.label_Balls = QtWidgets.QLabel(self.widget)
        self.label_Balls.setMaximumSize(QtCore.QSize(71, 51))
        self.label_Balls.setScaledContents(False)
        self.label_Balls.setWordWrap(True)
        self.label_Balls.setObjectName("label_Balls")
        self.gridLayout.addWidget(self.label_Balls, 2, 2, 1, 1)
        self.spinBox_SO = QtWidgets.QSpinBox(self.widget)
        self.spinBox_SO.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_SO.setObjectName("spinBox_SO")
        self.gridLayout.addWidget(self.spinBox_SO, 3, 0, 1, 1)
        self.spinBox_FB = QtWidgets.QSpinBox(self.widget)
        self.spinBox_FB.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_FB.setObjectName("spinBox_FB")
        self.gridLayout.addWidget(self.spinBox_FB, 3, 1, 1, 1)
        self.spinBox_Balls = QtWidgets.QSpinBox(self.widget)
        self.spinBox_Balls.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_Balls.setObjectName("spinBox_Balls")
        self.gridLayout.addWidget(self.spinBox_Balls, 3, 2, 1, 1)
        self.label_BB = QtWidgets.QLabel(self.widget)
        self.label_BB.setMaximumSize(QtCore.QSize(71, 51))
        self.label_BB.setScaledContents(False)
        self.label_BB.setWordWrap(True)
        self.label_BB.setObjectName("label_BB")
        self.gridLayout.addWidget(self.label_BB, 4, 0, 1, 1)
        self.label_PU = QtWidgets.QLabel(self.widget)
        self.label_PU.setMaximumSize(QtCore.QSize(71, 51))
        self.label_PU.setScaledContents(False)
        self.label_PU.setWordWrap(True)
        self.label_PU.setObjectName("label_PU")
        self.gridLayout.addWidget(self.label_PU, 4, 1, 1, 1)
        self.label_HR = QtWidgets.QLabel(self.widget)
        self.label_HR.setMaximumSize(QtCore.QSize(71, 51))
        self.label_HR.setScaledContents(False)
        self.label_HR.setWordWrap(True)
        self.label_HR.setObjectName("label_HR")
        self.gridLayout.addWidget(self.label_HR, 4, 2, 1, 1)
        self.spinBox_BB = QtWidgets.QSpinBox(self.widget)
        self.spinBox_BB.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_BB.setObjectName("spinBox_BB")
        self.gridLayout.addWidget(self.spinBox_BB, 5, 0, 1, 1)
        self.spinBox_PU = QtWidgets.QSpinBox(self.widget)
        self.spinBox_PU.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_PU.setObjectName("spinBox_PU")
        self.gridLayout.addWidget(self.spinBox_PU, 5, 1, 1, 1)
        self.spinBox_HR = QtWidgets.QSpinBox(self.widget)
        self.spinBox_HR.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_HR.setObjectName("spinBox_HR")
        self.gridLayout.addWidget(self.spinBox_HR, 5, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralWidget)
        self.widget1.setGeometry(QtCore.QRect(30, 320, 503, 194))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_Events = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget_Events.setObjectName("tableWidget_Events")
        self.tableWidget_Events.setColumnCount(2)
        self.tableWidget_Events.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Events.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Events.setHorizontalHeaderItem(1, item)
        self.tableWidget_Events.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget_Events, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_Delete = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout_2.addWidget(self.pushButton_Delete, 3, 0, 1, 1)
        self.pushButton_PU = QtWidgets.QPushButton(self.widget1)
        self.pushButton_PU.setObjectName("pushButton_PU")
        self.gridLayout_2.addWidget(self.pushButton_PU, 3, 2, 1, 1)
        self.pushButton_Walk = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Walk.setObjectName("pushButton_Walk")
        self.gridLayout_2.addWidget(self.pushButton_Walk, 2, 1, 1, 1)
        self.spinBox_AB_TBL = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_AB_TBL.setObjectName("spinBox_AB_TBL")
        self.gridLayout_2.addWidget(self.spinBox_AB_TBL, 1, 0, 1, 1)
        self.pushButton_SO = QtWidgets.QPushButton(self.widget1)
        self.pushButton_SO.setObjectName("pushButton_SO")
        self.gridLayout_2.addWidget(self.pushButton_SO, 1, 1, 1, 1)
        self.pushButton_GB = QtWidgets.QPushButton(self.widget1)
        self.pushButton_GB.setObjectName("pushButton_GB")
        self.gridLayout_2.addWidget(self.pushButton_GB, 1, 2, 1, 1)
        self.pushButton_FB = QtWidgets.QPushButton(self.widget1)
        self.pushButton_FB.setObjectName("pushButton_FB")
        self.gridLayout_2.addWidget(self.pushButton_FB, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 1)
        self.pushButton_Other = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Other.setObjectName("pushButton_Other")
        self.gridLayout_2.addWidget(self.pushButton_Other, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        Siera.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Siera)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1033, 21))
        self.menuBar.setObjectName("menuBar")
        self.menutitle = QtWidgets.QMenu(self.menuBar)
        self.menutitle.setObjectName("menutitle")
        Siera.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(Siera)
        self.statusBar.setObjectName("statusBar")
        Siera.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(Siera)
        self.mainToolBar.setObjectName("mainToolBar")
        Siera.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.menuBar.addAction(self.menutitle.menuAction())

        self.retranslateUi(Siera)
        QtCore.QMetaObject.connectSlotsByName(Siera)

    def retranslateUi(self, Siera):
        _translate = QtCore.QCoreApplication.translate
        Siera.setWindowTitle(_translate("Siera", "MainWindow"))
        self.label_SIERA.setText(_translate("Siera", "<html><head/><body><p><span style=\" font-size:18pt;\">SIERA HERE</span></p></body></html>"))
        self.label_SIERA_STD.setText(_translate("Siera", "<html><head/><body><p><span style=\" font-size:18pt;\">SIERA HERE</span></p></body></html>"))
        self.label_SIERA_label.setText(_translate("Siera", "<html><head/><body><p><span style=\" font-size:18pt;\">SIERA Below</span></p></body></html>"))
        self.label_SIERA_STD_label.setText(_translate("Siera", "<html><head/><body><p><span style=\" font-size:18pt;\">SIERA Standardized</span></p></body></html>"))
        self.label_PA.setText(_translate("Siera", "Plate Appearances"))
        self.label_GB.setText(_translate("Siera", "Number of Ground balls"))
        self.label_K.setText(_translate("Siera", "Number of Strikes"))
        self.label_SO.setText(_translate("Siera", "<html><head/><body><p>Strikeout Count</p></body></html>"))
        self.label_FB.setText(_translate("Siera", "<html><head/><body><p>Number of Fly balls </p></body></html>"))
        self.label_Balls.setText(_translate("Siera", "<html><head/><body><p>Number of Balls</p></body></html>"))
        self.label_BB.setText(_translate("Siera", "<html><head/><body><p>Base on Balls Count</p></body></html>"))
        self.label_PU.setText(_translate("Siera", "<html><head/><body><p>Number of Pop-ups</p></body></html>"))
        self.label_HR.setText(_translate("Siera", "<html><head/><body><p>Number of Home runs</p></body></html>"))
        item = self.tableWidget_Events.horizontalHeaderItem(0)
        item.setText(_translate("Siera", "At Bat Num"))
        item = self.tableWidget_Events.horizontalHeaderItem(1)
        item.setText(_translate("Siera", "Event"))
        self.label.setText(_translate("Siera", "At Bat"))
        self.pushButton_Delete.setText(_translate("Siera", "Delete Row"))
        self.pushButton_PU.setText(_translate("Siera", "Pop-Up"))
        self.pushButton_Walk.setText(_translate("Siera", "Walk"))
        self.pushButton_SO.setText(_translate("Siera", "Strikeout"))
        self.pushButton_GB.setText(_translate("Siera", "Ground Ball"))
        self.pushButton_FB.setText(_translate("Siera", "Fly Ball"))
        self.pushButton_Other.setText(_translate("Siera", "Other"))
        self.menutitle.setTitle(_translate("Siera", "title"))

