# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Siera(object):
    def setupUi(self, Siera):
        Siera.setObjectName("Siera")
        Siera.resize(842, 626)
        self.centralWidget = QtWidgets.QWidget(Siera)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setMaximumSize(QtCore.QSize(49, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 4, 1, 1)
        self.spinBox_start_year = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_start_year.setMaximumSize(QtCore.QSize(49, 20))
        self.spinBox_start_year.setMinimum(2000)
        self.spinBox_start_year.setMaximum(2018)
        self.spinBox_start_year.setProperty("value", 2016)
        self.spinBox_start_year.setObjectName("spinBox_start_year")
        self.gridLayout_5.addWidget(self.spinBox_start_year, 0, 5, 1, 1)
        self.lineEdit_player = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_player.setMaximumSize(QtCore.QSize(495, 20))
        self.lineEdit_player.setInputMask("")
        self.lineEdit_player.setObjectName("lineEdit_player")
        self.gridLayout_5.addWidget(self.lineEdit_player, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_FB = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_FB.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_FB.setObjectName("pushButton_FB")
        self.gridLayout_2.addWidget(self.pushButton_FB, 2, 2, 1, 1)
        self.pushButton_Other = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Other.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Other.setObjectName("pushButton_Other")
        self.gridLayout_2.addWidget(self.pushButton_Other, 3, 1, 1, 1)
        self.pushButton_PU = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_PU.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_PU.setObjectName("pushButton_PU")
        self.gridLayout_2.addWidget(self.pushButton_PU, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMaximumSize(QtCore.QSize(75, 62))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_AB_TBL = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_AB_TBL.setMaximumSize(QtCore.QSize(75, 20))
        self.spinBox_AB_TBL.setProperty("value", 1)
        self.spinBox_AB_TBL.setObjectName("spinBox_AB_TBL")
        self.gridLayout_2.addWidget(self.spinBox_AB_TBL, 1, 0, 1, 1)
        self.pushButton_Walk = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Walk.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Walk.setObjectName("pushButton_Walk")
        self.gridLayout_2.addWidget(self.pushButton_Walk, 2, 1, 1, 1)
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Delete.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout_2.addWidget(self.pushButton_Delete, 3, 0, 1, 1)
        self.label_Balls_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Balls_2.setMaximumSize(QtCore.QSize(71, 51))
        self.label_Balls_2.setScaledContents(False)
        self.label_Balls_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_Balls_2.setWordWrap(True)
        self.label_Balls_2.setObjectName("label_Balls_2")
        self.gridLayout_2.addWidget(self.label_Balls_2, 4, 2, 1, 1)
        self.spinBox_K = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_K.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_K.setObjectName("spinBox_K")
        self.gridLayout_2.addWidget(self.spinBox_K, 5, 0, 1, 1)
        self.pushButton_SO = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_SO.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_SO.setObjectName("pushButton_SO")
        self.gridLayout_2.addWidget(self.pushButton_SO, 1, 1, 1, 1)
        self.pushButton_GB = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_GB.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_GB.setObjectName("pushButton_GB")
        self.gridLayout_2.addWidget(self.pushButton_GB, 1, 2, 1, 1)
        self.label_Num_pitches = QtWidgets.QLabel(self.centralWidget)
        self.label_Num_pitches.setMaximumSize(QtCore.QSize(75, 31))
        self.label_Num_pitches.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Num_pitches.setObjectName("label_Num_pitches")
        self.gridLayout_2.addWidget(self.label_Num_pitches, 5, 2, 1, 1)
        self.label_Balls = QtWidgets.QLabel(self.centralWidget)
        self.label_Balls.setMaximumSize(QtCore.QSize(71, 51))
        self.label_Balls.setScaledContents(False)
        self.label_Balls.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_Balls.setWordWrap(True)
        self.label_Balls.setObjectName("label_Balls")
        self.gridLayout_2.addWidget(self.label_Balls, 4, 1, 1, 1)
        self.spinBox_Balls = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_Balls.setMaximumSize(QtCore.QSize(71, 31))
        self.spinBox_Balls.setObjectName("spinBox_Balls")
        self.gridLayout_2.addWidget(self.spinBox_Balls, 5, 1, 1, 1)
        self.label_K = QtWidgets.QLabel(self.centralWidget)
        self.label_K.setMaximumSize(QtCore.QSize(71, 51))
        self.label_K.setScaledContents(False)
        self.label_K.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_K.setWordWrap(True)
        self.label_K.setObjectName("label_K")
        self.gridLayout_2.addWidget(self.label_K, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.tableWidget_Events = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget_Events.setMaximumSize(QtCore.QSize(391, 245))
        self.tableWidget_Events.setObjectName("tableWidget_Events")
        self.tableWidget_Events.setColumnCount(2)
        self.tableWidget_Events.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Events.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Events.setHorizontalHeaderItem(1, item)
        self.tableWidget_Events.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget_Events, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Siera_stand_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Siera_stand_2.setMaximumSize(QtCore.QSize(6, 22))
        self.label_Siera_stand_2.setObjectName("label_Siera_stand_2")
        self.gridLayout_4.addWidget(self.label_Siera_stand_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setMaximumSize(QtCore.QSize(95, 22))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_GB_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_GB_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_GB_ct.setObjectName("label_GB_ct")
        self.gridLayout_4.addWidget(self.label_GB_ct, 6, 1, 1, 1)
        self.label_PA_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_PA_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_PA_ct.setObjectName("label_PA_ct")
        self.gridLayout_4.addWidget(self.label_PA_ct, 2, 1, 1, 1)
        self.label_Siera_ingame_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Siera_ingame_2.setMaximumSize(QtCore.QSize(6, 22))
        self.label_Siera_ingame_2.setObjectName("label_Siera_ingame_2")
        self.gridLayout_4.addWidget(self.label_Siera_ingame_2, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setMaximumSize(QtCore.QSize(95, 22))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(95, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_SO_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_SO_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_SO_ct.setObjectName("label_SO_ct")
        self.gridLayout_4.addWidget(self.label_SO_ct, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMaximumSize(QtCore.QSize(95, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_Siera_stand = QtWidgets.QLabel(self.centralWidget)
        self.label_Siera_stand.setMaximumSize(QtCore.QSize(95, 22))
        self.label_Siera_stand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Siera_stand.setObjectName("label_Siera_stand")
        self.gridLayout_4.addWidget(self.label_Siera_stand, 1, 0, 1, 1)
        self.label_Walk_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_Walk_ct.setMaximumSize(QtCore.QSize(6, 21))
        self.label_Walk_ct.setObjectName("label_Walk_ct")
        self.gridLayout_4.addWidget(self.label_Walk_ct, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setMaximumSize(QtCore.QSize(95, 22))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_Other_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_Other_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_Other_ct.setObjectName("label_Other_ct")
        self.gridLayout_4.addWidget(self.label_Other_ct, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setMaximumSize(QtCore.QSize(95, 22))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_PU_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_PU_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_PU_ct.setObjectName("label_PU_ct")
        self.gridLayout_4.addWidget(self.label_PU_ct, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setMaximumSize(QtCore.QSize(95, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_FB_ct = QtWidgets.QLabel(self.centralWidget)
        self.label_FB_ct.setMaximumSize(QtCore.QSize(6, 22))
        self.label_FB_ct.setObjectName("label_FB_ct")
        self.gridLayout_4.addWidget(self.label_FB_ct, 7, 1, 1, 1)
        self.label_Siera_ingame = QtWidgets.QLabel(self.centralWidget)
        self.label_Siera_ingame.setMaximumSize(QtCore.QSize(95, 22))
        self.label_Siera_ingame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Siera_ingame.setObjectName("label_Siera_ingame")
        self.gridLayout_4.addWidget(self.label_Siera_ingame, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 11)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setMaximumSize(QtCore.QSize(34, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 1, 1, 1)
        self.pushButton_player = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_player.setObjectName("pushButton_player")
        self.gridLayout_5.addWidget(self.pushButton_player, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setMaximumSize(QtCore.QSize(43, 20))
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 6, 1, 1)
        self.spinBox_end_year = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_end_year.setMaximumSize(QtCore.QSize(49, 20))
        self.spinBox_end_year.setMinimum(2000)
        self.spinBox_end_year.setMaximum(2018)
        self.spinBox_end_year.setProperty("value", 2016)
        self.spinBox_end_year.setObjectName("spinBox_end_year")
        self.gridLayout_5.addWidget(self.spinBox_end_year, 0, 7, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.plotWidget = MplWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_6.addWidget(self.plotWidget, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 0, 1, 1)
        Siera.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Siera)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 842, 21))
        self.menuBar.setObjectName("menuBar")
        self.menutitle = QtWidgets.QMenu(self.menuBar)
        self.menutitle.setObjectName("menutitle")
        Siera.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(Siera)
        self.statusBar.setObjectName("statusBar")
        Siera.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(Siera)
        self.mainToolBar.setObjectName("mainToolBar")
        Siera.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.menuBar.addAction(self.menutitle.menuAction())

        self.retranslateUi(Siera)
        QtCore.QMetaObject.connectSlotsByName(Siera)

    def retranslateUi(self, Siera):
        _translate = QtCore.QCoreApplication.translate
        Siera.setWindowTitle(_translate("Siera", "MainWindow"))
        self.label_10.setText(_translate("Siera", "Start Year"))
        self.lineEdit_player.setPlaceholderText(_translate("Siera", "Enter Player"))
        self.pushButton_FB.setText(_translate("Siera", "Fly Ball"))
        self.pushButton_Other.setText(_translate("Siera", "Other"))
        self.pushButton_PU.setText(_translate("Siera", "Pop-Up"))
        self.label.setText(_translate("Siera", "At Bat"))
        self.pushButton_Walk.setText(_translate("Siera", "Walk"))
        self.pushButton_Delete.setText(_translate("Siera", "Delete Row"))
        self.label_Balls_2.setText(_translate("Siera", "<html><head/><body><p>Number of Pitches</p></body></html>"))
        self.pushButton_SO.setText(_translate("Siera", "Strikeout"))
        self.pushButton_GB.setText(_translate("Siera", "Ground Ball"))
        self.label_Num_pitches.setText(_translate("Siera", "0"))
        self.label_Balls.setText(_translate("Siera", "<html><head/><body><p>Number of Balls</p></body></html>"))
        self.label_K.setText(_translate("Siera", "Number of Strikes"))
        self.tableWidget_Events.setSortingEnabled(True)
        item = self.tableWidget_Events.horizontalHeaderItem(0)
        item.setText(_translate("Siera", "At Bat Num"))
        item = self.tableWidget_Events.horizontalHeaderItem(1)
        item.setText(_translate("Siera", "Event"))
        self.label_Siera_stand_2.setText(_translate("Siera", "0"))
        self.label_4.setText(_translate("Siera", "#GB"))
        self.label_GB_ct.setText(_translate("Siera", "0"))
        self.label_PA_ct.setText(_translate("Siera", "0"))
        self.label_Siera_ingame_2.setText(_translate("Siera", "0"))
        self.label_8.setText(_translate("Siera", "# PA"))
        self.label_2.setText(_translate("Siera", "# SO"))
        self.label_SO_ct.setText(_translate("Siera", "0"))
        self.label_3.setText(_translate("Siera", "# Walks"))
        self.label_Siera_stand.setText(_translate("Siera", "SIERA standardized"))
        self.label_Walk_ct.setText(_translate("Siera", "0"))
        self.label_5.setText(_translate("Siera", "# Other"))
        self.label_Other_ct.setText(_translate("Siera", "0"))
        self.label_7.setText(_translate("Siera", "#FB"))
        self.label_PU_ct.setText(_translate("Siera", "0"))
        self.label_6.setText(_translate("Siera", "#PU"))
        self.label_FB_ct.setText(_translate("Siera", "0"))
        self.label_Siera_ingame.setText(_translate("Siera", "SIERA in game"))
        self.label_9.setText(_translate("Siera", "Player:"))
        self.pushButton_player.setText(_translate("Siera", "Load Player"))
        self.label_11.setText(_translate("Siera", "End Year"))
        self.menutitle.setTitle(_translate("Siera", "title"))

from mplwidget import MplWidget
